import type { Volunteer } from '../types';

// Forty volunteers across the food bank's active pool. ~40% (16/40)
// arrived via VIEW corporate partners — the eight CloudMotion folks
// here are the same humans who appear on the corporate-side employee
// roster, which is the load-bearing argument for "VIEW makes data
// flow between workspaces." The remaining ~60% are direct community
// signups and legacy records imported from the food bank's old CRM.
//
// Detail richness scales with demo importance — the volunteers
// linked from the workbench (Marcus Lee, Connie Albright) and a
// representative sample carry full skills/notes/history. The rest
// are seeded with enough that the list view feels populated.

export const NP_VOLUNTEERS: Volunteer[] = [

  // ============================================================
  // CloudMotion (10) — VIEW-sourced, same humans as the corporate
  // employee roster
  // ============================================================

  {
    id: 'nv-marcus-lee',
    name: 'Marcus Lee',
    employer: 'CloudMotion',
    email: 'marcus.lee@cloudmotion.com',
    totalHours: 24,
    eventsAttended: 4,
    lastActive: '2026-04-10',
    source: 'view-partner',
    sourcePartnerId: 'cp-cloudmotion',
    status: 'active',
    recognitions: [],
    skills: [
      { label: 'Spanish-speaking', source: 'view-partner' },
      { label: 'Data viz', source: 'view-partner' },
    ],
    notes: [
      { id: 'n-ml-1', date: '2026-04-11', author: 'Maria Velasquez', body: 'Stayed past the shift to help with breakdown. Worth a recognition note in the next cycle.' },
      { id: 'n-ml-2', date: '2025-12-13', author: 'Maria Velasquez', body: 'First-time check-in. Engineering team lead. Strong line discipline.' },
    ],
    history: [
      { id: 'e1', date: '2026-04-10', title: 'Spring Service Day — Food Sort & Repack', partner: 'CloudMotion', hours: 3, source: 'view-partner' },
      { id: 'e3', date: '2025-12-12', title: 'Winter Holiday Food Drive Pack', partner: 'CloudMotion', hours: 3, source: 'view-partner' },
      { id: 'h-cm-3', date: '2025-09-20', title: 'Back-to-School Snack Pack Drive', partner: 'CloudMotion', hours: 3, source: 'view-partner' },
      { id: 'h-cm-4', date: '2025-06-14', title: 'Summer Service Saturday', partner: 'CloudMotion', hours: 3, source: 'view-partner' },
    ],
    joinedAt: '2025-06-14',
  },
  {
    id: 'nv-priya-raman',
    name: 'Priya Raman',
    employer: 'CloudMotion',
    email: 'priya.raman@cloudmotion.com',
    totalHours: 12,
    eventsAttended: 2,
    lastActive: '2025-12-12',
    source: 'view-partner',
    sourcePartnerId: 'cp-cloudmotion',
    status: 'active',
    recognitions: [],
    skills: [
      { label: 'Photography', source: 'direct' },
    ],
    notes: [
      { id: 'n-pr-1', date: '2025-12-13', author: 'Maria Velasquez', body: 'Brought a camera. Photos came out great — used three in our newsletter.' },
    ],
    history: [
      { id: 'e3', date: '2025-12-12', title: 'Winter Holiday Food Drive Pack', partner: 'CloudMotion', hours: 6, source: 'view-partner' },
      { id: 'h-cm-3', date: '2025-09-20', title: 'Back-to-School Snack Pack Drive', partner: 'CloudMotion', hours: 6, source: 'view-partner' },
    ],
    joinedAt: '2025-09-20',
  },
  {
    id: 'nv-daniel-okonkwo',
    name: 'Daniel Okonkwo',
    employer: 'CloudMotion',
    email: 'daniel.okonkwo@cloudmotion.com',
    totalHours: 6,
    eventsAttended: 1,
    lastActive: '2025-12-12',
    source: 'view-partner',
    sourcePartnerId: 'cp-cloudmotion',
    status: 'active',
    recognitions: [],
    skills: [],
    notes: [
      { id: 'n-do-1', date: '2025-12-13', author: 'Maria Velasquez', body: 'Signed up but no check-in scan recorded — flagged in reconciliation. Likely attended; resolving with CloudMotion.' },
    ],
    history: [
      { id: 'e3', date: '2025-12-12', title: 'Winter Holiday Food Drive Pack', partner: 'CloudMotion', hours: 6, source: 'view-partner' },
    ],
    joinedAt: '2025-12-12',
  },
  {
    id: 'nv-jenna-park',
    name: 'Jenna Park',
    employer: 'CloudMotion',
    email: 'jenna.park@cloudmotion.com',
    totalHours: 21,
    eventsAttended: 4,
    lastActive: '2026-04-10',
    source: 'view-partner',
    sourcePartnerId: 'cp-cloudmotion',
    status: 'active',
    recognitions: [],
    skills: [
      { label: 'Inventory tooling', source: 'view-partner' },
    ],
    notes: [],
    history: [
      { id: 'e1', date: '2026-04-10', title: 'Spring Service Day — Food Sort & Repack', partner: 'CloudMotion', hours: 3, source: 'view-partner' },
      { id: 'h-cm-5', date: '2025-03-08', title: 'Q1 Skills-Based: Inventory Audit Help', partner: 'CloudMotion', hours: 9, source: 'view-partner' },
      { id: 'e3', date: '2025-12-12', title: 'Winter Holiday Food Drive Pack', partner: 'CloudMotion', hours: 3, source: 'view-partner' },
      { id: 'h-cm-3', date: '2025-09-20', title: 'Back-to-School Snack Pack Drive', partner: 'CloudMotion', hours: 6, source: 'view-partner' },
    ],
    joinedAt: '2025-03-08',
  },
  {
    id: 'nv-aisha-patel',
    name: 'Aisha Patel',
    employer: 'CloudMotion',
    email: 'aisha.patel@cloudmotion.com',
    totalHours: 15,
    eventsAttended: 3,
    lastActive: '2026-04-10',
    source: 'view-partner',
    sourcePartnerId: 'cp-cloudmotion',
    status: 'active',
    recognitions: [],
    skills: [],
    notes: [],
    history: [
      { id: 'e1', date: '2026-04-10', title: 'Spring Service Day — Food Sort & Repack', partner: 'CloudMotion', hours: 3, source: 'view-partner' },
      { id: 'e3', date: '2025-12-12', title: 'Winter Holiday Food Drive Pack', partner: 'CloudMotion', hours: 6, source: 'view-partner' },
      { id: 'h-cm-3', date: '2025-09-20', title: 'Back-to-School Snack Pack Drive', partner: 'CloudMotion', hours: 6, source: 'view-partner' },
    ],
    joinedAt: '2025-09-20',
  },
  {
    id: 'nv-roman-ito',
    name: 'Roman Ito',
    employer: 'CloudMotion',
    email: 'roman.ito@cloudmotion.com',
    totalHours: 9,
    eventsAttended: 2,
    lastActive: '2026-04-10',
    source: 'view-partner',
    sourcePartnerId: 'cp-cloudmotion',
    status: 'active',
    recognitions: [],
    skills: [],
    notes: [],
    history: [
      { id: 'e1', date: '2026-04-10', title: 'Spring Service Day — Food Sort & Repack', partner: 'CloudMotion', hours: 3, source: 'view-partner' },
      { id: 'e3', date: '2025-12-12', title: 'Winter Holiday Food Drive Pack', partner: 'CloudMotion', hours: 6, source: 'view-partner' },
    ],
    joinedAt: '2025-12-12',
  },
  {
    id: 'nv-mei-tanaka',
    name: 'Mei Tanaka',
    employer: 'CloudMotion',
    email: 'mei.tanaka@cloudmotion.com',
    totalHours: 18,
    eventsAttended: 3,
    lastActive: '2025-12-12',
    source: 'view-partner',
    sourcePartnerId: 'cp-cloudmotion',
    status: 'active',
    recognitions: [],
    skills: [
      { label: 'Photography', source: 'direct' },
    ],
    notes: [
      { id: 'n-mt-1', date: '2025-12-18', author: 'Maria Velasquez', body: 'Submitted retroactive 3h request — was at the event but check-in scanner failed. Cross-reference with CloudMotion confirmed. Approved.' },
    ],
    history: [
      { id: 'e3', date: '2025-12-12', title: 'Winter Holiday Food Drive Pack', partner: 'CloudMotion', hours: 6, source: 'view-partner' },
      { id: 'h-cm-3', date: '2025-09-20', title: 'Back-to-School Snack Pack Drive', partner: 'CloudMotion', hours: 6, source: 'view-partner' },
      { id: 'h-cm-4', date: '2025-06-14', title: 'Summer Service Saturday', partner: 'CloudMotion', hours: 6, source: 'view-partner' },
    ],
    joinedAt: '2025-06-14',
  },
  {
    id: 'nv-carlos-reyes',
    name: 'Carlos Reyes',
    employer: 'CloudMotion',
    email: 'carlos.reyes@cloudmotion.com',
    totalHours: 31,
    eventsAttended: 5,
    lastActive: '2026-04-10',
    source: 'view-partner',
    sourcePartnerId: 'cp-cloudmotion',
    status: 'active',
    recognitions: [],
    skills: [
      { label: 'Spanish-speaking', source: 'view-partner' },
      { label: 'Forklift-certified', source: 'direct' },
    ],
    notes: [
      { id: 'n-cr-1', date: '2026-01-04', author: 'Maria Velasquez', body: 'Stayed an extra hour at the December drive. Retro request for 4h approved.' },
    ],
    history: [
      { id: 'e1', date: '2026-04-10', title: 'Spring Service Day — Food Sort & Repack', partner: 'CloudMotion', hours: 3, source: 'view-partner' },
      { id: 'e3', date: '2025-12-12', title: 'Winter Holiday Food Drive Pack', partner: 'CloudMotion', hours: 7, source: 'view-partner' },
      { id: 'h-cm-3', date: '2025-09-20', title: 'Back-to-School Snack Pack Drive', partner: 'CloudMotion', hours: 6, source: 'view-partner' },
      { id: 'h-cm-4', date: '2025-06-14', title: 'Summer Service Saturday', partner: 'CloudMotion', hours: 6, source: 'view-partner' },
      { id: 'h-cm-5', date: '2025-03-08', title: 'Q1 Skills-Based: Inventory Audit', partner: 'CloudMotion', hours: 9, source: 'view-partner' },
    ],
    joinedAt: '2025-03-08',
  },
  {
    id: 'nv-vivian-holloway',
    name: 'Vivian Holloway',
    employer: 'CloudMotion',
    email: 'vivian.holloway@cloudmotion.com',
    totalHours: 6,
    eventsAttended: 1,
    lastActive: '2026-04-10',
    source: 'view-partner',
    sourcePartnerId: 'cp-cloudmotion',
    status: 'active',
    recognitions: [],
    skills: [],
    notes: [],
    history: [
      { id: 'e1', date: '2026-04-10', title: 'Spring Service Day — Food Sort & Repack', partner: 'CloudMotion', hours: 6, source: 'view-partner' },
    ],
    joinedAt: '2026-04-10',
  },
  {
    id: 'nv-theo-brennan',
    name: 'Theo Brennan',
    employer: 'CloudMotion',
    email: 'theo.brennan@cloudmotion.com',
    totalHours: 9,
    eventsAttended: 2,
    lastActive: '2026-04-10',
    source: 'view-partner',
    sourcePartnerId: 'cp-cloudmotion',
    status: 'active',
    recognitions: [],
    skills: [],
    notes: [],
    history: [
      { id: 'e1', date: '2026-04-10', title: 'Spring Service Day — Food Sort & Repack', partner: 'CloudMotion', hours: 3, source: 'view-partner' },
      { id: 'h-cm-4', date: '2025-06-14', title: 'Summer Service Saturday', partner: 'CloudMotion', hours: 6, source: 'view-partner' },
    ],
    joinedAt: '2025-06-14',
  },

  // ============================================================
  // Nest & Foundry (3)
  // ============================================================

  {
    id: 'nv-yumiko-hayashi',
    name: 'Yumiko Hayashi',
    employer: 'Nest & Foundry',
    email: 'yumiko@nestfoundry.com',
    totalHours: 18,
    eventsAttended: 2,
    lastActive: '2026-03-28',
    source: 'view-partner',
    sourcePartnerId: 'cp-nestfoundry',
    status: 'active',
    recognitions: ['first-skills-based'],
    skills: [
      { label: 'Brand design', source: 'view-partner' },
      { label: 'Print production', source: 'view-partner' },
    ],
    notes: [
      { id: 'n-yh-1', date: '2026-03-30', author: 'Maria Velasquez', body: 'Lead on the toolkit refresh. Volunteer welcome packet redesign was hers.' },
    ],
    history: [
      { id: 'h-nf-1', date: '2026-03-28', title: 'Brand refresh consultation', partner: 'Nest & Foundry', hours: 6, source: 'view-partner' },
      { id: 'h-nf-2', date: '2026-02-08', title: 'Saturday Sort Shift', partner: 'Nest & Foundry', hours: 3, source: 'view-partner' },
      { id: 'h-nf-3', date: '2025-11-15', title: 'Holiday Sort Shift', partner: 'Nest & Foundry', hours: 9, source: 'view-partner' },
    ],
    joinedAt: '2025-11-15',
  },
  {
    id: 'nv-owen-caldwell',
    name: 'Owen Caldwell',
    employer: 'Nest & Foundry',
    email: 'owen@nestfoundry.com',
    totalHours: 9,
    eventsAttended: 2,
    lastActive: '2026-03-28',
    source: 'view-partner',
    sourcePartnerId: 'cp-nestfoundry',
    status: 'active',
    recognitions: [],
    skills: [
      { label: 'Brand strategy', source: 'view-partner' },
    ],
    notes: [],
    history: [
      { id: 'h-nf-1', date: '2026-03-28', title: 'Brand refresh consultation', partner: 'Nest & Foundry', hours: 6, source: 'view-partner' },
      { id: 'h-nf-2', date: '2026-02-08', title: 'Saturday Sort Shift', partner: 'Nest & Foundry', hours: 3, source: 'view-partner' },
    ],
    joinedAt: '2026-02-08',
  },
  {
    id: 'nv-nadia-reyes',
    name: 'Nadia Reyes',
    employer: 'Nest & Foundry',
    email: 'nadia@nestfoundry.com',
    totalHours: 6,
    eventsAttended: 1,
    lastActive: '2026-03-28',
    source: 'view-partner',
    sourcePartnerId: 'cp-nestfoundry',
    status: 'active',
    recognitions: [],
    skills: [
      { label: 'UX research', source: 'view-partner' },
    ],
    notes: [
      { id: 'n-nr-1', date: '2026-03-29', author: 'Maria Velasquez', body: 'Asked about pro-bono usability work for our donor portal — worth a follow-up if N&F has bandwidth in Q3.' },
    ],
    history: [
      { id: 'h-nf-1', date: '2026-03-28', title: 'Brand refresh consultation', partner: 'Nest & Foundry', hours: 6, source: 'view-partner' },
    ],
    joinedAt: '2026-03-28',
  },

  // ============================================================
  // Bramble Health (2)
  // ============================================================

  {
    id: 'nv-elena-marsh',
    name: 'Elena Marsh',
    employer: 'Bramble Health',
    email: 'elena.marsh@bramble.health',
    totalHours: 6,
    eventsAttended: 2,
    lastActive: '2026-04-05',
    source: 'view-partner',
    sourcePartnerId: 'cp-bramblehealth',
    status: 'active',
    recognitions: [],
    skills: [],
    notes: [],
    history: [
      { id: 'h-bh-1', date: '2026-04-05', title: 'Spring Distribution Drive', partner: 'Bramble Health', hours: 3, source: 'view-partner' },
      { id: 'h-bh-2', date: '2025-10-18', title: 'First-time partner shift', partner: 'Bramble Health', hours: 3, source: 'view-partner' },
    ],
    joinedAt: '2025-10-18',
  },
  {
    id: 'nv-devon-pham',
    name: 'Devon Pham',
    employer: 'Bramble Health',
    email: 'devon.pham@bramble.health',
    totalHours: 3,
    eventsAttended: 1,
    lastActive: '2026-04-05',
    source: 'view-partner',
    sourcePartnerId: 'cp-bramblehealth',
    status: 'active',
    recognitions: [],
    skills: [
      { label: 'Engineering', source: 'view-partner' },
    ],
    notes: [],
    history: [
      { id: 'h-bh-1', date: '2026-04-05', title: 'Spring Distribution Drive', partner: 'Bramble Health', hours: 3, source: 'view-partner' },
    ],
    joinedAt: '2026-04-05',
  },

  // ============================================================
  // Cardinal Logistics (1)
  // ============================================================

  {
    id: 'nv-rashid-bashar',
    name: 'Rashid Bashar',
    employer: 'Cardinal Logistics',
    email: 'rashid.bashar@cardinallogistics.com',
    totalHours: 39,
    eventsAttended: 4,
    lastActive: '2025-11-14',
    source: 'view-partner',
    sourcePartnerId: 'cp-cardinal',
    status: 'inactive',
    recognitions: [],
    skills: [
      { label: 'IT systems', source: 'view-partner' },
      { label: 'Operations', source: 'view-partner' },
    ],
    notes: [
      { id: 'n-rb-1', date: '2025-08-04', author: 'Maria Velasquez', body: 'Mentioned at the picnic that he\'d like to help with our IT setup. Renée has bandwidth, allegedly. Never followed up.' },
    ],
    history: [
      { id: 'h-cl-1', date: '2025-11-14', title: 'Veterans Day Sort Shift', partner: 'Cardinal Logistics', hours: 3, source: 'view-partner' },
      { id: 'h-cl-2', date: '2024-12-08', title: 'Holiday Drive 2024', partner: 'Cardinal Logistics', hours: 6, source: 'view-partner' },
      { id: 'h-cl-3', date: '2024-08-17', title: 'Back-to-School Drive', partner: 'Cardinal Logistics', hours: 6, source: 'view-partner' },
      { id: 'h-cl-4', date: '2024-04-13', title: 'Spring Service Day', partner: 'Cardinal Logistics', hours: 24, source: 'view-partner' },
    ],
    joinedAt: '2024-04-13',
  },

  // ============================================================
  // Direct community signups (13)
  // ============================================================

  {
    id: 'nv-alma-quintero',
    name: 'Alma Quintero',
    employer: null,
    email: 'aquinte79@gmail.com',
    phone: '512-555-0142',
    totalHours: 96,
    eventsAttended: 14,
    lastActive: '2026-04-12',
    source: 'direct',
    status: 'active',
    recognitions: ['10-events', 'spanish-speaker'],
    skills: [
      { label: 'Spanish-speaking', source: 'direct' },
      { label: 'Distribution lead-ready', source: 'direct' },
    ],
    notes: [
      { id: 'n-aq-1', date: '2025-09-12', author: 'Maria Velasquez', body: 'Steady second-Saturday volunteer for two years. Showed three new community volunteers the line yesterday — natural lead.' },
    ],
    history: [
      { id: 'h-com-1', date: '2026-04-12', title: 'Second Saturday Sort', partner: null, hours: 4, source: 'direct' },
      { id: 'h-com-2', date: '2026-03-08', title: 'Second Saturday Sort', partner: null, hours: 4, source: 'direct' },
      { id: 'h-com-3', date: '2026-02-08', title: 'Second Saturday Sort', partner: null, hours: 4, source: 'direct' },
    ],
    joinedAt: '2024-03-09',
  },
  {
    id: 'nv-fernando-salazar',
    name: 'Fernando Salazar',
    employer: null,
    email: 'fsalazar@txmail.com',
    totalHours: 42,
    eventsAttended: 7,
    lastActive: '2026-03-08',
    source: 'direct',
    status: 'active',
    recognitions: [],
    skills: [{ label: 'Spanish-speaking', source: 'direct' }],
    notes: [],
    history: [
      { id: 'h-com-2', date: '2026-03-08', title: 'Second Saturday Sort', partner: null, hours: 6, source: 'direct' },
      { id: 'h-com-3', date: '2026-02-08', title: 'Second Saturday Sort', partner: null, hours: 6, source: 'direct' },
    ],
    joinedAt: '2025-02-08',
  },
  {
    id: 'nv-beatrice-whitfield',
    name: 'Beatrice Whitfield',
    employer: null,
    email: 'bwhitfield@gmail.com',
    totalHours: 124,
    eventsAttended: 19,
    lastActive: '2026-04-12',
    source: 'direct',
    status: 'active',
    recognitions: ['10-events'],
    skills: [{ label: 'Driver-certified', source: 'direct' }],
    notes: [
      { id: 'n-bw-1', date: '2025-11-02', author: 'Maria Velasquez', body: 'Has her own pickup truck. Regularly volunteers to do the Maverick run when their driver can\'t.' },
    ],
    history: [],
    joinedAt: '2023-08-12',
  },
  {
    id: 'nv-jamal-underwood',
    name: 'Jamal Underwood',
    employer: null,
    email: 'jamal.underwood@gmail.com',
    totalHours: 18,
    eventsAttended: 3,
    lastActive: '2026-04-12',
    source: 'direct',
    status: 'active',
    recognitions: [],
    skills: [],
    notes: [],
    history: [],
    joinedAt: '2025-12-06',
  },
  {
    id: 'nv-pilar-castellanos-vol',
    name: 'Pilar Castellanos',
    employer: null,
    email: 'pilar.c@gmail.com',
    totalHours: 84,
    eventsAttended: 11,
    lastActive: '2026-04-15',
    source: 'direct',
    status: 'active',
    recognitions: ['10-events'],
    skills: [{ label: 'Logistics', source: 'direct' }],
    notes: [
      { id: 'n-pc-1', date: '2024-06-04', author: 'Maria Velasquez', body: 'Maverick Foods contact volunteers personally. Different hat — same human.' },
    ],
    history: [],
    joinedAt: '2023-11-04',
  },
  {
    id: 'nv-henry-atwood',
    name: 'Henry Atwood',
    employer: null,
    email: 'hatwood@msn.com',
    totalHours: 36,
    eventsAttended: 6,
    lastActive: '2026-03-08',
    source: 'direct',
    status: 'active',
    recognitions: [],
    skills: [],
    notes: [],
    history: [],
    joinedAt: '2025-04-12',
  },
  {
    id: 'nv-sasha-petrov-vincent',
    name: 'Sasha Petrov-Vincent',
    employer: null,
    email: 'sasha.pv@gmail.com',
    totalHours: 12,
    eventsAttended: 2,
    lastActive: '2026-02-08',
    source: 'direct',
    status: 'active',
    recognitions: [],
    skills: [{ label: 'Russian-speaking', source: 'direct' }],
    notes: [],
    history: [],
    joinedAt: '2025-12-06',
  },
  {
    id: 'nv-mateo-vasquez',
    name: 'Mateo Vasquez',
    employer: null,
    email: 'mateov@gmail.com',
    totalHours: 60,
    eventsAttended: 9,
    lastActive: '2026-04-12',
    source: 'direct',
    status: 'active',
    recognitions: ['spanish-speaker'],
    skills: [{ label: 'Spanish-speaking', source: 'direct' }],
    notes: [],
    history: [],
    joinedAt: '2024-09-14',
  },
  {
    id: 'nv-ginger-whitley',
    name: 'Ginger Whitley',
    employer: null,
    email: 'gingerw@gmail.com',
    totalHours: 24,
    eventsAttended: 4,
    lastActive: '2026-04-12',
    source: 'direct',
    status: 'active',
    recognitions: [],
    skills: [],
    notes: [],
    history: [],
    joinedAt: '2025-09-13',
  },
  {
    id: 'nv-levi-munro',
    name: 'Levi Munro',
    employer: null,
    email: 'levi.munro@yahoo.com',
    totalHours: 9,
    eventsAttended: 2,
    lastActive: '2026-03-08',
    source: 'direct',
    status: 'active',
    recognitions: [],
    skills: [],
    notes: [],
    history: [],
    joinedAt: '2026-02-08',
  },
  {
    id: 'nv-kanya-suriyong',
    name: 'Kanya Suriyong',
    employer: null,
    email: 'kanya.s@gmail.com',
    totalHours: 21,
    eventsAttended: 4,
    lastActive: '2026-04-12',
    source: 'direct',
    status: 'active',
    recognitions: [],
    skills: [{ label: 'Thai-speaking', source: 'direct' }],
    notes: [],
    history: [],
    joinedAt: '2025-08-09',
  },
  {
    id: 'nv-briana-hutchins',
    name: 'Briana Hutchins',
    employer: null,
    email: 'briana.h@gmail.com',
    totalHours: 48,
    eventsAttended: 8,
    lastActive: '2026-04-12',
    source: 'direct',
    status: 'active',
    recognitions: [],
    skills: [{ label: 'ASL-interpreter', source: 'direct' }],
    notes: [
      { id: 'n-bh-1', date: '2025-04-12', author: 'Maria Velasquez', body: 'ASL-fluent. Can be paired with Deaf volunteers when we have a need.' },
    ],
    history: [],
    joinedAt: '2024-12-07',
  },
  {
    id: 'nv-eli-rosenfeld',
    name: 'Eli Rosenfeld',
    employer: null,
    email: 'erosenfeld@gmail.com',
    totalHours: 30,
    eventsAttended: 5,
    lastActive: '2026-04-12',
    source: 'direct',
    status: 'active',
    recognitions: [],
    skills: [],
    notes: [],
    history: [],
    joinedAt: '2025-06-14',
  },

  // ============================================================
  // Imported / legacy from prior CRM (11)
  // ============================================================

  {
    id: 'nv-connie-albright',
    name: 'Connie Albright',
    employer: null,
    email: 'connie.albright@earthlink.net',
    phone: '512-555-0388',
    totalHours: 612,
    eventsAttended: 87,
    lastActive: '2026-04-12',
    source: 'imported',
    status: 'active',
    recognitions: ['10-events', '25-events', '50-events'],
    skills: [
      { label: 'Spanish-speaking', source: 'imported' },
      { label: 'Distribution lead', source: 'imported' },
      { label: 'Trains new volunteers', source: 'direct' },
    ],
    notes: [
      { id: 'n-ca-1', date: '2025-04-04', author: 'Maria Velasquez', body: 'Twelve-year volunteer. Distribution lead on Tuesdays. The most reliable person on this list.' },
      { id: 'n-ca-2', date: '2025-04-12', author: 'Maria Velasquez', body: 'Connie hit 50 events in our records. Letter going out with the quarterly recognition mailer. (Actual count is higher — we lost some pre-2018 records in the migration.)' },
    ],
    history: [],
    joinedAt: '2014-02-15',
  },
  { id: 'nv-royce-pemberton-vol', name: 'Royce Pemberton', employer: null, email: 'rpemberton@hcmail.com', totalHours: 144, eventsAttended: 22, lastActive: '2026-03-20', source: 'imported', status: 'active', recognitions: ['10-events', '25-events'], skills: [], notes: [{ id: 'n-rp-1', date: '2024-08-22', author: 'Maria Velasquez', body: 'Hill Country Bank contact. Volunteers personally as well — different from his role at the bank.' }], history: [], joinedAt: '2017-09-08' },
  { id: 'nv-marisol-tejeda',  name: 'Marisol Tejeda',  employer: null, email: 'mtejeda@gmail.com', totalHours: 312, eventsAttended: 48, lastActive: '2026-04-12', source: 'imported', status: 'active', recognitions: ['10-events', '25-events'], skills: [{ label: 'Spanish-speaking', source: 'imported' }], notes: [], history: [], joinedAt: '2018-03-10' },
  { id: 'nv-hank-lieberman-vol',name: 'Hank Lieberman', employer: null, email: 'hank.lieberman@gmail.com', totalHours: 78, eventsAttended: 12, lastActive: '2025-08-30', source: 'imported', status: 'inactive', recognitions: ['10-events'], skills: [], notes: [], history: [], joinedAt: '2019-11-09' },
  { id: 'nv-dottie-crawford',  name: 'Dottie Crawford', employer: null, email: 'dottiec@aol.com', totalHours: 222, eventsAttended: 34, lastActive: '2026-03-08', source: 'imported', status: 'active', recognitions: ['10-events', '25-events'], skills: [{ label: 'Driver-certified', source: 'imported' }], notes: [], history: [], joinedAt: '2018-06-09' },
  { id: 'nv-solomon-adekunle', name: 'Solomon Adekunle', employer: null, email: 'sadekunle@gmail.com', totalHours: 96, eventsAttended: 16, lastActive: '2026-04-12', source: 'imported', status: 'active', recognitions: ['10-events'], skills: [], notes: [], history: [], joinedAt: '2020-10-10' },
  { id: 'nv-lacey-friedrichs', name: 'Lacey Friedrichs', employer: null, email: 'laceyf@gmail.com', totalHours: 54, eventsAttended: 8, lastActive: '2026-02-08', source: 'imported', status: 'active', recognitions: [], skills: [], notes: [], history: [], joinedAt: '2021-04-10' },
  { id: 'nv-augusto-vega',     name: 'Augusto Vega',    employer: null, email: 'augusto.vega@gmail.com', totalHours: 168, eventsAttended: 25, lastActive: '2026-04-12', source: 'imported', status: 'active', recognitions: ['10-events', '25-events'], skills: [{ label: 'Forklift-certified', source: 'imported' }, { label: 'Spanish-speaking', source: 'imported' }], notes: [], history: [], joinedAt: '2019-05-11' },
  { id: 'nv-tabatha-hines',    name: 'Tabatha Hines',   employer: null, email: 'tabatha.hines@gmail.com', totalHours: 36, eventsAttended: 6, lastActive: '2025-11-09', source: 'imported', status: 'inactive', recognitions: [], skills: [], notes: [], history: [], joinedAt: '2022-02-12' },
  { id: 'nv-eddie-boon-choi-vol', name: 'Eddie Boon-Choi', employer: null, email: 'eddie.bc@gmail.com', totalHours: 102, eventsAttended: 17, lastActive: '2026-04-02', source: 'imported', status: 'active', recognitions: ['10-events'], skills: [{ label: 'Logistics', source: 'imported' }], notes: [{ id: 'n-eb-1', date: '2024-06-04', author: 'Maria Velasquez', body: 'Travis Energy contact volunteers personally. Same person, different hat.' }], history: [], joinedAt: '2020-01-11' },
  { id: 'nv-lillian-reeves',   name: 'Lillian Reeves',  employer: null, email: 'lillianr@gmail.com', totalHours: 90, eventsAttended: 14, lastActive: '2026-04-12', source: 'imported', status: 'active', recognitions: ['10-events'], skills: [], notes: [], history: [], joinedAt: '2021-09-11' },
];

export const NP_VOLUNTEER_BY_ID = (id: string): Volunteer | undefined =>
  NP_VOLUNTEERS.find(v => v.id === id);
